### ISSUE TITLE
FR: `jj config unset [OPTIONS] <--user|--repo> <NAME>`

### ISSUE THREAD

**Issue by Veykril** [martinvonz/jj#4458]
**Is your feature request related to a problem? Please describe.**
Removing a configuration currently requires editing the file manually, having this command makes the removal of configs more convenient.

**Describe the solution you'd like**
Have a `jj config` subcommand that removes any set config by the given name.

**Describe alternatives you've considered**
None

**Additional context**
This would give parity with git's config command, which likewise offers an `unset` subcommand

**Comment by pylbrecht** [comment]
I have been lurking for a while now and this seems like a great opportunity to get involved.

Disclaimer: as a full-time working father of two my progress usually is slow but steady. In case that becomes a problem, let me know.

**Comment by pylbrecht** [comment]
Do we want to follow git's behavior for `unset`; removing empty tables, which are the result of an `unset`?

## Example

Before
```toml
[table]
foo = true

[another-table]
bar = true
```

Unset `another-table.bar`, which results in `another-table` being empty:
```shell
$ jj config unset another-table.bar
```

After
```toml
[table]
foo = true
```

---

..and should such removals recursively bubble up to the config root?

Before
```toml
[table]
foo = true

[another-table]
inline-table = { foo = false }
```

Unset `another-table.inline-table.foo`, which results in `another-table.inline-table` being empty, which in turn results in `another-table` being empty:
```shell
$ jj unset another-table.inline-table.foo
```

After (empty config)
```toml
[table]
foo = true
```

---

To me this is the most intuitive, but I would like to confirm before spending time on implementing it.
