### ISSUE TITLE
FR/RFC: allow edit/diff/merge-tools to have warnings or be explicitly disallowed

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#4549]
It is currently difficult to deprecate merge tools. I also wonder how many people run `jj split --tool vscode` and get a non-functional interface.

To address this, we could reorganize `merge-tools.toml` ([current state](https://github.com/martinvonz/jj/blob/64e1ae277db390989a6deb8f5a1a4bc62fa0e570/cli/src/config/merge_tools.toml)) and merge tool config a bit; I was thinking about how to do it for a while. One possibility is to change `edit-args` to `edit.args`, and then add a few fields to allow the following:

```toml
[merge-tools.meld]
merge.args = ["$left", "$base", "$right", "-o", "$output", "--auto-merge"]

[merge-tools.vscode]
program = "code"
diff = { error = true }
# error = "message" also allowed, error=true gives a generic message:
# "The tool `vscode` cannot be used for diff editing", etc.
edit = { error = true }
merge = {
  args = ["--wait", "--merge", "$left", "$right", "$base", "$output"]
  edits-conflict-markers = true
  warning = "This tool is deprecated and will soon be removed. Use `code` instead"
}

[merge-tools.code]
# ...
```

We could also rename the whole `[merge-tools]` table while we are at it, but I wouldn't do it unless we can come up with a great name. I don't like `[tools]` or `[external-tools]` since there are also a different category of tools for `jj fix`, unless we want those to be `tools.NAME.fix` (which might not make much sense, their config is very different).
